import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import DateTimePicker, { type DateTimePickerEvent } from '@react-native-community/datetimepicker';
import { router } from 'expo-router';
import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { ScreenContainer } from '../../src/components/common/ScreenContainer';
import { PrimaryButton } from '../../src/components/common/PrimaryButton';
import { AppHeader } from '../../src/components/common/AppHeader';
import { useAuthStore } from '../../src/store/authStore';
import { usePlayers, playerKeys } from '../../src/features/player/api';
import { profileApi, profileValues, validateProfile, resolvePlayerProfile, type ProfileValues } from '../../src/features/player/profile';
import { colors, radius, shadows, spacing } from '../../src/theme';

const genderOptions = ['MALE', 'FEMALE', 'OTHER'] as const;
const dateFromValue = (value: string) => { const [year, month, day] = value.split('-').map(Number); return year && month && day ? new Date(year, month - 1, day) : new Date(2000, 0, 1); };
const valueFromDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;

export default function ProfileEdit() {
  const user = useAuthStore((state) => state.user); const query = usePlayers(); const client = useQueryClient(); const existing = resolvePlayerProfile(query.data ?? [], user);
  const [v, setV] = useState<ProfileValues>(profileValues(existing)); const [mobile, setMobile] = useState(user?.mobile || existing?.mobile || ''); const [errors, setErrors] = useState<Partial<Record<keyof ProfileValues, string>>>({}); const [submitError, setSubmitError] = useState(''); const [dobPicker, setDobPicker] = useState(false);
  const m = useMutation({ mutationFn: async () => { if (existing) return profileApi.update(existing.id, v, mobile.trim()); const created = await profileApi.create(v, mobile.trim()); if (user) return profileApi.linkUser(created.id, user.id); return created; }, onSuccess: async (profile: any) => { await client.invalidateQueries({ queryKey: playerKeys.players }); if (user) useAuthStore.setState({ user: { ...user, playerProfile: { id: profile.id, playerCode: profile.playerCode } } }); router.back(); }, onError: (e: any) => setSubmitError(e?.message || 'Unable to save your profile. Try again.') });
  const set = (key: keyof ProfileValues) => (value: string) => setV((prev) => ({ ...prev, [key]: value }));
  const submit = () => { if (m.isPending) return; setSubmitError(''); const nextErrors = validateProfile(v); if (!mobile.trim()) (nextErrors as any).mobile = 'Mobile number is required'; setErrors(nextErrors); if (Object.keys(nextErrors).length) return; m.mutate(); };
  const selectDate = (event: DateTimePickerEvent, date?: Date) => { setDobPicker(false); if (event.type !== 'dismissed' && date) set('dob')(valueFromDate(date)); };
  const field = (label: string, icon: string, key: keyof ProfileValues, placeholder: string, options?: { keyboardType?: 'default' | 'number-pad'; editable?: boolean; multiline?: boolean }) => <View style={s.fieldGroup}><Text style={s.label}>{label}</Text><View style={[s.inputShell, errors[key] && s.inputError]}><Text style={s.icon}>{icon}</Text><TextInput accessibilityLabel={label} placeholder={placeholder} placeholderTextColor={colors.muted} value={v[key] as string} onChangeText={set(key)} style={[s.input, options?.multiline && s.multiline]} keyboardType={options?.keyboardType} editable={options?.editable !== false} multiline={options?.multiline} textAlignVertical={options?.multiline ? 'top' : 'center'}/></View>{errors[key] && <Text style={s.error}>{errors[key]}</Text>}</View>;
  return <ScreenContainer><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={s.content}><AppHeader title={existing ? 'Edit Profile' : 'Create Profile'} eyebrow="SMASHPOINT · PLAYER" back/><Text style={s.subtitle}>Set up your player profile to get started</Text><View style={s.card}>
    {field('Full name', '◉', 'fullName', 'Enter your full name')}
    <View style={s.fieldGroup}><Text style={s.label}>Mobile number</Text><View style={[s.inputShell, !mobile.trim() && s.inputError]}><Text style={s.icon}>⌕</Text><TextInput accessibilityLabel="Mobile number" value={mobile} onChangeText={setMobile} style={s.input} keyboardType="phone-pad" editable={!existing} placeholder="Mobile number" placeholderTextColor={colors.muted}/></View>{(errors as any).mobile && <Text style={s.error}>{(errors as any).mobile}</Text>}</View>
    <View style={s.fieldGroup}><Text style={s.label}>Gender</Text><View style={s.choiceRow}>{genderOptions.map(option => <Pressable key={option} accessibilityRole="button" onPress={() => setV(prev => ({ ...prev, gender: option }))} style={[s.choice, v.gender === option && s.choiceSelected]}><Text style={[s.choiceText, v.gender === option && s.choiceTextSelected]}>{option[0] + option.slice(1).toLowerCase()}</Text></Pressable>)}</View>{errors.gender && <Text style={s.error}>{errors.gender}</Text>}</View>
    <View style={s.fieldGroup}><Text style={s.label}>Date of birth</Text><Pressable accessibilityRole="button" accessibilityLabel="Date of birth" onPress={() => setDobPicker(true)} style={[s.inputShell, errors.dob && s.inputError]}><Text style={s.icon}>□</Text><Text style={v.dob ? s.dateValue : s.placeholder}>{v.dob || 'DD / MM / YYYY'}</Text><Text style={s.calendar}>⌄</Text></Pressable>{dobPicker && <DateTimePicker value={dateFromValue(v.dob)} mode="date" display="default" onChange={selectDate}/>}<Text style={s.hint}>Stored as YYYY-MM-DD</Text>{errors.dob && <Text style={s.error}>{errors.dob}</Text>}</View>
    {field('Location', '⌖', 'location', 'Enter city / location')}
    {field('Playing since', '⌁', 'playingSince', 'Year, e.g. 2019', { keyboardType: 'number-pad' })}
    <View style={s.fieldGroup}><Text style={s.label}>Regular player?</Text><View style={s.choiceRow}>{(['YES', 'NO'] as const).map(option => <Pressable key={option} accessibilityRole="button" onPress={() => setV(prev => ({ ...prev, regularPlayer: option }))} style={[s.choice, s.choiceWide, v.regularPlayer === option && s.choiceSelected]}><Text style={[s.choiceText, v.regularPlayer === option && s.choiceTextSelected]}>{option === 'YES' ? 'Yes' : 'No'}</Text></Pressable>)}</View>{errors.regularPlayer && <Text style={s.error}>{errors.regularPlayer}</Text>}</View>
    {v.regularPlayer === 'YES' && field('Court / Academy', '▣', 'courtAcademy', 'Enter court or academy name')}
    {submitError ? <Text style={s.submitError}>{submitError}</Text> : null}<PrimaryButton disabled={m.isPending} title={m.isPending ? 'Creating profile…' : existing ? 'Save changes  →' : 'Create Profile  →'} onPress={submit}/>
  </View></ScrollView></ScreenContainer>;
}

const s = StyleSheet.create({ content: { paddingBottom: spacing.xl }, subtitle: { color: colors.muted, fontSize: 14, marginBottom: spacing.md }, card: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, ...shadows.card }, fieldGroup: { marginBottom: spacing.md }, label: { color: colors.text, fontSize: 13, fontWeight: '800', marginBottom: spacing.xs }, inputShell: { minHeight: 52, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceTint, borderWidth: 1, borderColor: colors.border, borderRadius: radius.medium, paddingHorizontal: spacing.md }, input: { flex: 1, color: colors.text, fontSize: 15, paddingVertical: 12 }, multiline: { minHeight: 88 }, icon: { color: colors.primary, fontSize: 19, width: 28, textAlign: 'center', marginRight: spacing.xs }, placeholder: { color: colors.muted, flex: 1, fontSize: 15 }, dateValue: { color: colors.text, flex: 1, fontSize: 15 }, calendar: { color: colors.primary, fontSize: 22 }, hint: { color: colors.muted, fontSize: 11, marginTop: 4 }, inputError: { borderColor: colors.error }, choiceRow: { flexDirection: 'row', gap: spacing.sm }, choice: { flex: 1, minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: radius.medium, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceTint }, choiceWide: { flex: 1 }, choiceSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.secondary, fontWeight: '800' }, choiceTextSelected: { color: colors.white }, error: { color: colors.error, fontSize: 12, marginTop: 5 }, submitError: { color: colors.error, marginBottom: spacing.md, lineHeight: 18 } });
